projeto01/Areas/Cadastros/Controllers/ProdutosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Modelo.Cadastros;
using Modelo.Tabelas;
using System.Data.Entity;
using System.Net;
using Servicos.Cadastros;
using Servicos.Tabelas;
using System.IO;

namespace Projeto01.Areas.Cadastros.Controllers
{
    public class ProdutosController : Controller
    {
        // GET: Produtos

        private ProdutoServico produtoServico = new ProdutoServico();
        private FabricanteServico fabricanteServico = new FabricanteServico();
        private CategoriaServico categoriaServico = new CategoriaServico();

        public ActionResult Index()
        {
            return View(produtoServico.ObterProdutosClassificadosPorNome());
        }

        public ActionResult Create()
        {
            PopularViewBag();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Produto produto, HttpPostedFileBase logotipo = null, string chkRemoverImagem = null)
        {

            return GravarProduto(produto, logotipo, chkRemoverImagem);
        }

        public ActionResult Edit(long id)
        {
            PopularViewBag(produtoServico.ObterProdutoPorId(id));
            return ObterVisaoProdutoPorId(id);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Produto produto, HttpPostedFileBase logotipo = null, string chkRemoverImagem = null)
        {
            return GravarProduto(produto, logotipo, chkRemoverImagem);
        }


        public ActionResult Details(long id)
        {
            return ObterVisaoProdutoPorId(id);
        }

        public ActionResult Delete(long? id)
        {
            return ObterVisaoProdutoPorId(id);
        }

        // POST: Produtos/Delete/5
        [HttpPost]
        public ActionResult Delete(long id)
        {
            try
            {
                Produto produto = produtoServico.EliminarProdutoPorId(id);
                TempData["Message"] = "Produto " + produto.Nome.ToUpper() + " foi removido";
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }



        private ActionResult ObterVisaoProdutoPorId(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Produto produto = produtoServico.ObterProdutoPorId((long)id);

            if (produto == null)
            {
                return HttpNotFound();
            }
            return View(produto);
        }




        //Veja que, na assinatura do método, o parâmetro produto é
        //opcional.E quando ele não existir, é atribuído null a ele.Isso foi
        //adotado para podermos diferenciar quando o quarto parâmetro do
        //SelectList() será informado.
        private void PopularViewBag(Produto produto = null)
        {
            if (produto == null)
            {
                ViewBag.CategoriaId = new SelectList(categoriaServico.ObterCategoriasClassificadasPorNome(), "CategoriaId", "Nome");
                ViewBag.FabricanteId = new SelectList(fabricanteServico.ObterFabricantesClassificadosPorNome(), "FabricanteId", "Nome");
            }
            else
            {
                ViewBag.CategoriaId = new SelectList(categoriaServico.ObterCategoriasClassificadasPorNome(), "CategoriaId", "Nome", produto.CategoriaId);
                ViewBag.FabricanteId = new SelectList(fabricanteServico.ObterFabricantesClassificadosPorNome(), "FabricanteId", "Nome", produto.FabricanteId);
            }
        }

        private byte[] SetLogotipo(HttpPostedFileBase logotipo)
        {
            var bytesLogotipo = new byte[logotipo.ContentLength];
            logotipo.InputStream.Read(bytesLogotipo, 0, logotipo.ContentLength);
            return bytesLogotipo;
        }

        public FileContentResult GetLogotipo(long id)
        {
            Produto produto = produtoServico.ObterProdutoPorId(id);
            if (produto != null)
            {
                return File(produto.Logotipo, produto.LogotipoMimeType);
            }
            return null;
        }

        public ActionResult DownloadArquivo(long id)
        {
            Produto produto = produtoServico.ObterProdutoPorId(id);
            FileStream fileStream = new FileStream(Server.MapPath("~/TempData/"+produto.NomeArquivo), FileMode.Create, FileAccess.Write);
            fileStream.Write(produto.Logotipo, 0, Convert.ToInt32(produto.TamanhoArquivo));
            fileStream.Close();
            return File(fileStream.Name, produto.LogotipoMimeType, produto.NomeArquivo);
        }

        private ActionResult GravarProduto(Produto produto, HttpPostedFileBase logotipo, string chkRemoverImagem)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (chkRemoverImagem != null)
                    {
                        produto.Logotipo = null;
                    }
                    if (logotipo != null)
                    {
                        produto.LogotipoMimeType = logotipo.ContentType;
                        produto.Logotipo = SetLogotipo(logotipo);

                        produto.NomeArquivo = logotipo.FileName;
                        produto.TamanhoArquivo = logotipo.ContentLength;
                    }
                    produtoServico.GravarProduto(produto);
                    return RedirectToAction("Index");
                }
                PopularViewBag(produto);
                return View(produto);
            }
            catch
            {
                PopularViewBag(produto);
                return View(produto);
            }
        }

        public JsonResult GetProdutosPorNome(string param)
        {
            var r = produtoServico.ObterProdutosPorNome(param);
            return Json(r, JsonRequestBehavior.AllowGet);
        }
    }
}

projeto01/Areas/Carrinho/Controllers/CarrinhosController.cs
using Modelo.Carrinho;
using Servicos.Cadastros;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace projeto01.Areas.Carrinho.Controllers
{
    
    public class CarrinhosController : Controller
    {

        private ProdutoServico produtoServico = new ProdutoServico();
        // GET: Carrinho/Carrinhos
        public ActionResult Create()
        {

            //inicia recuperando uma variável chamada carrinho da sessão existente no contexto da requisição HTTP.
            IEnumerable<ItemCarrinho> carrinho = HttpContext.Session["carrinho"] as IEnumerable<ItemCarrinho>;


            //Caso a variável seja nula, significa que está ocorrendo a primeira requisição do
            //cliente para esta action / visão, o que leva, então, a criação da variável na sessão,  antes de retorná-la.
            if (carrinho == null)
            {
                carrinho = new List<ItemCarrinho>();
                HttpContext.Session["carrinho"] = carrinho;
            }
            return View(carrinho);
        }





        [HttpPost]
        [ValidateAntiForgeryToken]
        public PartialViewResult AddProduto(FormCollection collection)
        {
            List<ItemCarrinho> carrinho = HttpContext.Session["carrinho"] as List<ItemCarrinho>;

            var produto = produtoServico.ObterProdutoPorId(Convert.ToInt32(collection.Get("idproduto")));
            var itemCarrinho = new ItemCarrinho()
            {
                Produto = produto,
                Quantidade = 1,
                ValorUnitario = produto.ValorUnitario
            };
            carrinho.Add(itemCarrinho);
            HttpContext.Session["carrinho"] = carrinho;
            return PartialView("_ItensCarrinho", carrinho);
        }
    }
}

projeto01/Areas/Carrinho/Views/Carrinhos/Create.cshtml
@model IEnumerable<Modelo.Carrinho.ItemCarrinho>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("AddProduto", "Carrinhos", new { area = "Carrinho" }, FormMethod.Post, new { id = "formCarrinho" }))
{
    @Html.AntiForgeryToken()
    <div class="panel panel-primary">
        <div class="panel-heading">
        </div>
        <div class="panel-body">
            <div class="form-horizontal">
                <div class="col-md-12">
                    <div class="form-group">
                        Digite o nome do produto e confirme a inserção
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="form-group">
                        @Html.Hidden("idproduto")
                        @Html.Label("Produto para pesquisar ")
                        <!-- COMENTÁRIO 1
                        O ELEMENTO A SEGUIR SERÁ DE AUTOCOMP
                        LEMENTO, VIA AJAX, POR MEIO DE UM CONTROLE jQUERY -->
                        @Html.TextBox("nomeproduto", "", new { @class = "form-control autocomplete - with - update - field", data_updatefield = "idproduto", data_url = Url.Action("GetProdutosPorNome", "Produtos", new { Area = "Cadastros" }) })
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group" style="text-align:center;">
                    <input id="SubmitForm" type="submit" value="Adicionar produto ao carrinho" class="btn btn-success" />
                </div>
            </div>
        </div>
    </div>
    <div class="panel panel-primary">
        <div class="panel-body">
            <div class="col-md-12">
                <!-- COMENTÁRIO 2
                O DIV A SEGUIR TERÁ SEU CONTEÚDO ATUALIZADO VIA
                234 9.3 A VISÃO PARA O CARRINHO DE COMPRA
                AJAX A CADA INSERÇÃO DE ITEM NO CARRINHO -->
                <div id="itenscarrinho">
                    @Html.Partial("~/Areas/Carrinho/Views/Carrinhos/_ItensCarrinho.cshtml", Model)
                </div>
            </div>
        </div>
    </div>
}

@section styles{
    <link href="~/Scripts/jquery-ui-1.11.4.custom/jquery-ui.css" rel="stylesheet" />
}
@section ScriptPage {
    <script src="~/Scripts/jquery-ui-1.11.4.custom/jquery-ui.js">
    </script>

    <script type="text/javascript">
        $(document).ready(function (response, status, xhr) {
            $('.autocomplete-with-update-field').autocomplete(
                {
                    minLength: 5,

                    source: function (request, response) {
                        var url = $(this.element).data('url');
                        $.getJSON(url, { param: request.term },
                            function (data) {
                                response(data);
                            });
                    },

                    select: function (event, ui) {
                        var updatefield = '#' + $("#" + event.target.id).data('updatefield');
                        $(updatefield).val(ui.item.id);
                        setTimeout(function () {
                            $(updatefield).focus();
                        }, 200);
                    }
                });
    </script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('li').removeClass("active");
            $('#liCarrinho').addClass("active");
        });
    </script>
}

projeto01/Areas/Carrinho/Views/Carrinhos/_ItensCarrinho.cshtml
@model IEnumerable<Modelo.Carrinho.ItemCarrinho>
<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>
                Produto
            </th>
            <th>
                Quantidade
            </th>
            <th>Valor</th>
            <th>SubTotal</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Produto.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantidade)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ValorUnitario)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SubTotal)
                </td>
            </tr>
        }
    </tbody>
</table>
Total Carrinho:
@{ var totalCarrinho = Model.Sum(s => s.SubTotal);}
@totalCarrinho