projeto01/Areas/Carrinho/Controllers/CarrinhosController.cs
using Modelo.Carrinho;
using Servicos.Cadastros;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace projeto01.Areas.Carrinho.Controllers
{
    
    public class CarrinhosController : Controller
    {

        private ProdutoServico produtoServico = new ProdutoServico();
        // GET: Carrinho/Carrinhos
        public ActionResult Create()
        {

            //inicia recuperando uma variável chamada carrinho da sessão existente no contexto da requisição HTTP.
            IEnumerable<ItemCarrinho> carrinho = HttpContext.Session["carrinho"] as IEnumerable<ItemCarrinho>;


            //Caso a variável seja nula, significa que está ocorrendo a primeira requisição do
            //cliente para esta action / visão, o que leva, então, a criação da variável na sessão,  antes de retorná-la.
            if (carrinho == null)
            {
                carrinho = new List<ItemCarrinho>();
                HttpContext.Session["carrinho"] = carrinho;
            }
            return View(carrinho);
        }





        [HttpPost]
        [ValidateAntiForgeryToken]
        public PartialViewResult AddProduto(FormCollection collection)
        {
            List<ItemCarrinho> carrinho = HttpContext.Session["carrinho"] as List<ItemCarrinho>;

            var produto = produtoServico.ObterProdutoPorId(Convert.ToInt32(collection.Get("idproduto")));
            var itemCarrinho = new ItemCarrinho()
            {
                Produto = produto,
                Quantidade = 1,
                ValorUnitario = produto.ValorUnitario
            };
            carrinho.Add(itemCarrinho);
            HttpContext.Session["carrinho"] = carrinho;
            return PartialView("_ItensCarrinho", carrinho);
        }
    }
}

projeto01/Areas/Seguranca/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity.Owin;
using projeto01.Infraestrutura; 


namespace projeto01.Areas.Seguranca.Controllers
{
    public class AdminController : Controller
    {
        // GET: Seguranca/Admin
        public ActionResult Index()
        {
            return View(GerenciadorUsuario.Users);
        }

        private GerenciadorUsuario GerenciadorUsuario
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<GerenciadorUsuario>();
            }
        }
    }
}

projeto01/Areas/Seguranca/Controllers/PapelAdminController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using projeto01.Infraestrutura;
using projeto01.Areas.Seguranca.Data;
using System.Web;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Collections.Generic;
using System.Net;

namespace projeto01.Areas.Seguranca.Controllers
{
    public class PapelAdminController : Controller
    {
        // GET: Seguranca/PapelAdmin
        [Authorize]
        public ActionResult Index()
        {
            return View(RoleManager.Roles);
        }

        private GerenciadorPapel RoleManager
        {
            get
            {
                return HttpContext.GetOwinContext().
                GetUserManager<GerenciadorPapel>();
            }
        }

        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        private void AddErrorsFromResult(IdentityResult result)
        {
            foreach (string error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }

        private GerenciadorUsuario UserManager
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<GerenciadorUsuario>();
            }
        }


        [HttpPost]
        public ActionResult Create([Required]string nome)
        {
            if (ModelState.IsValid)
            {
                IdentityResult result = RoleManager.Create(new Papel(nome));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    AddErrorsFromResult(result);
                }
            }
            return View(nome);
        }

        public ActionResult Edit(string id)
        {
            Papel papel = RoleManager.FindById(id);
            string[] memberIDs = papel.Users.Select(x => x.UserId).ToArray();

            IEnumerable<Usuario> membros = UserManager.Users.Where(x => memberIDs.Any(y => y == x.Id));
            IEnumerable<Usuario> naoMembros = UserManager.Users.Except(membros);

            return View(new PapelEditModel
            {
                Papel = papel,
                Membros = membros,
                NaoMembros = naoMembros
            });
        }


        [HttpPost]
        public ActionResult Edit(PapelModificationModel model)
        {
            IdentityResult result;
            if (ModelState.IsValid)
            {
                foreach (string userId in model.IdsParaAdicionar ?? new string[] { })
                {
                    result = UserManager.AddToRole(userId, model.NomePapel);

                    if (!result.Succeeded)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                }

                foreach (string userId in model.IdsParaRemover ?? new string[] { })
                {
                    result = UserManager.RemoveFromRole(userId, model.NomePapel);
                    if (!result.Succeeded)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                }
                return RedirectToAction("Index");
            }
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }
    }
}

projeto01/Controllers/FabrincatesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Projeto01.Context;
using Projeto01.Models;

namespace Projeto01.Controllers
{
    public class FabrincatesController : Controller
    {
        EFContext context = new EFContext();

        // GET: Fabrincates
        public ActionResult Index()
        {
            return View(context.fabricantes.ToList());
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Fabricante fabricante)
        {
            if (ModelState.IsValid)
            {
                context.fabricantes.Add(fabricante);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return View(fabricante);
            }

        }

        public ActionResult Edit(long? Id)
        {
            if (Id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (context.fabricantes.Find(Id) == null)
            {
                return HttpNotFound();
            }
            return View(context.fabricantes.Find(Id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Fabricante fabricante)
        {
            if (ModelState.IsValid)
            {
                context.Entry(fabricante).State = System.Data.Entity.EntityState.Modified;
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return View(fabricante);
            }

        }

        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (context.fabricantes.Find(id) == null)
            {
                return HttpNotFound();
            }

            return View(context.fabricantes.Find(id));

        }

        public ActionResult Delete(long? id)
        {


            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }
            if (context.fabricantes.Find(id) == null)
            {
                return HttpNotFound();
            }

            return View(context.fabricantes.Find(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Fabricante fabricante)
        {


            context.fabricantes.Remove(context.fabricantes.Find(fabricante.FabricanteID));
            context.SaveChanges();
            return RedirectToAction("Index");

        }
    }
}

projeto01/Views/Shared/_Layout.cshtml
@using projeto01.Infraestrutura
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width,
    initial-scale=1.0" charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/content/bootstrap.css")" rel="stylesheet" />
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="page-header bg-danger">
                <div>
                    <h1>
                        Desenvolvimento em ASP.NET MVC <small class="text-danger">Utilizando o Bootstrap</small>
                    </h1>
                </div>

                <div>

                    @if (Html.GetAuthenticatedUser().ToString() != "")
                    {
                        @Html.GetAuthenticatedUser();
                        @Html.ActionLink(" - Sair", "Logout", "Account");
                    }
                    else
                    {
                        @Html.ActionLink("Acessar", "Login", "Account", new { area = "Seguranca" }, null);
                    }

                </div>
            </div>



        </div>
        <div class="row  ">
            <div class="col-xs-3 col-md-3 bg-success">
                <ul class="nav nav-pills nav-stacked">
                    <li id="liHome" role="presentation" class="active"><hr /></li>
                    <li id="liHome" role="presentation" class="active"><a href="#">Home</a></li>
                    <li id="liCategorias" role="presentation"> @Html.ActionLink("Categorias", "Index", "Categorias", new { Area = "Tabelas" }, new { }) </li>
                    <li id="liCategorias" role="presentation"> @Html.ActionLink("Fabricantes", "Index", "Fabrincates", new { Area = "Cadastros" }, new { }) </li>
                    <li id="liProdutos" role="presentation">@Html.ActionLink("Produtos", "Index", "Produtos", new { Area = "Cadastros" }, new { }) </li>

                    <li id="liUsuarios" role="presentation">@Html.ActionLink("Usuarios", "Index", "Admin", new { Area = "Seguranca" }, new { }) </li>
                    <li id="liPapeisUsuarios" role="presentation">@Html.ActionLink("Papéis", "Index", "PapelAdmin", new { Area = "Seguranca" }, new { }) </li>

                    <li id="liCarrinho" role="presentation">@Html.ActionLink("Carrinho de compra", "Create", "Carrinhos", new { Area = "Carrinho" }, new { }) </li>
                </ul>
            </div>
            <div class="col-xs-9 col-md-9">
                <br />
                @RenderBody()
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-xs-12 col-md-12 bg-danger">
                <small>
                    &copy; 2019  All Rights Reserved

                    <a href="http://github/fausio.com">     GuidHub    </a>   |
                    <a href="http://facebook.com/fausioluis">     Facebook    </a>  |
                    <a href="#" >     Instagram    </a> |
                    <a href="#">     Twittwer </a>
                </small>
            </div>
        </div>
    </div>
    <script src="@Url.Content("~/scripts/jquery-1.10.2.js")"></script>
    <script src="@Url.Content("~/scripts/bootstrap.js")"></script>

    <script src="@Url.Content("~/Scripts/jquery.validate.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.js")"></script>

    @RenderSection("ScriptPage", required: false)
    @RenderSection("styles", required: false)



</body>
</html>