projeto01/Models/Categoria.cs
using projeto01.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Projeto01.Models
{
    public class Categoria
    {
        public long CategoriaId { get; set; }
        public string Nome { get; set; }

        public virtual ICollection<Produto> Produtos { get; set; }
    }
}

projeto01/Areas/Tabelas/Controllers/Controllers/CategoriasController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Servicos.Tabelas;
using Modelo.Cadastros;
using Modelo.Tabelas;

namespace Projeto01.Areas.Tabelas.Controllers
{
    public class CategoriasController : Controller
    {
        CategoriaServico CategoriaServico = new CategoriaServico();
        // GET: Fabricantes
        public ActionResult Index()
        {

            return View(CategoriaServico.ObterCategoriasClassificadasPorNome());
        }

        public ActionResult Edit(long id)
        {
            return View(CategoriaServico.FindCategoriaById(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Categoria categoria)
        {

            return this.GravarCategoria(categoria);
        }

        public ActionResult Details(long id)
        {
            #region   /* aqui no include escrevemos o nome do produto do context nao do modelo*/
            //return View(context.categorias.Where(x => x.CategoriaId == id).Include("Produtos.Fabricante").First());
            #endregion

            return View(CategoriaServico.FindCategoriaById(id));
        }

        public ActionResult Delete(long id)
        {
            return View(CategoriaServico.FindCategoriaById(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Categoria categoria)
        {
            var c = CategoriaServico.FindCategoriaById(categoria.CategoriaId);
            CategoriaServico.RemoveCategoria(c.CategoriaId);
            
            TempData["Message"] = "Categoria " + c.Nome + " removida com sucesso";
            return RedirectToAction("Index");

        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Categoria categoria)
        {
            return this.GravarCategoria(categoria);
        }

        public ActionResult GravarCategoria(Categoria categoria)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    CategoriaServico.GravarCategoria(categoria);
                    return RedirectToAction("Index");
                }
                else
                {
                    return View(categoria);
                }
            }
            catch (Exception)
            {

                return View(categoria);
            }
        }

    }
}

projeto01/Areas/Tabelas/Views/Categorias/Create.cshtml
@model Modelo.Tabelas.Categoria


@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Registro de uma nova CATEGORIA";
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="panel panel-primary">
        <div class="panel-heading">
            Registro de uma nova CATEGORIA
        </div>
        <div class="panel-body">
            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
        <div class="panel-footer panel-info">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Adicionar" class="btn btn-success" />
                @Html.ActionLink("Retornar para a listagem", "Index", null, new { @class = "btn btn-warning" })
            </div>
            <br />
            <br />
        </div>
    </div>
}
@section ScriptPage {
    <script src="~/Scripts/jquery.validate.min.js">
    </script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js">
    </script>


    <script type="text/javascript">
        $(document).ready(function () {
            $('li').removeClass("active");
            $('#liCategorias').addClass("active");
        });
    </script>
}

projeto01/Areas/Tabelas/Views/Categorias/Delete.cshtml
@model Modelo.Tabelas.Categoria


@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title =
    "Visualizando detalhes de uma CATEGORIA";
}




<div class="panel panel-primary">
    <div class="panel-heading">
        Dados da categoria a ser removido
    </div>
    <div class="panel-body">
        <div class="form-group">
            @Html.LabelFor(model => model.Nome)<br />
            <div class="input-group">
                <span class="input-group-addon">
                    <i class="glyphicon glyphicon-user"> </i>
                </span>
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
            </div>
        </div>
    </div>
    <div class="panel-footer panel-info">
        @*@using (Html.BeginForm())
        {
            @Html.HiddenFor(model => model.CategoriaId)
            @Html.AntiForgeryToken()
            <input type="submit" value="Remover FABRICANTE" class="btn btn-danger" />
            @Html.ActionLink("Retornar para a listagem de CATEGORIA", "Index", null, new { @class = "btn btn-info" })
        }*@

        <a href="#" class="btn btn-info" data-toggle="modal" data-target="#deleteConfirmationModal">Remover</a> @** aqui está o botao que chama o modal *@
        @Html.ActionLink("Retornar para a listagem", "Index", null, new { @class = "btn btn-info" })
    </div>
</div>



<div class="modal fade" id="deleteConfirmationModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title">
                    Confirmação de exclusão do  Categoria
                </h4>
            </div>
            <div class="modal-body">
                <p>
                    Você está prestes a remover a categoria @Model.Nome.ToUpper() do cadastro.
                </p>
                <p>
                    <strong>
                        Você está certo que deseja prosseguir?
                    </strong>
                </p>
                @using (Html.BeginForm("Delete", "Categorias", FormMethod.Post, new { @id = "delete-form", role = "form" }))

                {
                    @Html.HiddenFor(m => m.CategoriaId)
                    @Html.AntiForgeryToken()
                }

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" onclick="$('#delete-form').submit();">
                    Sim, exclua este categoria.
                </button>
                <button type="button" class="btn btn-primary" data-dismiss="modal">
                    Não, não exclua este categoria.
                </button>
            </div>
        </div>
    </div>
</div>

@Html.Partial("~/Areas/Cadastros/Views/Produtos/_PorCategoria.cshtml", Model.Produtos.ToList())

@section ScriptPage {
    <script type="text/javascript">
        $(document).ready(function () {
            $('li').removeClass("active");
            $('#liCategorias').addClass("active");
        });
    </script>
}

projeto01/Areas/Tabelas/Views/Categorias/Details.cshtml
@model Modelo.Tabelas.Categoria


@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title =
    "Visualizando detalhes de uma CATEGORIA";
}
<div class="panel panel-primary">
    <div class="panel-heading">
        Visualizando detalhes de uma CATEGORIA
    </div>
    <div class="panel-body">
        <div class="form-group">
            @Html.LabelFor(model => model.Nome)
            <br />
            <div class="input-group">
                <span class="input-group-addon">
                    <i class="glyphicon glyphicon-user"></i>
                </span>
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
            </div>
        </div>
    </div>
    <div class="panel-footer panel-info">
        @Html.ActionLink("Alterar", "Edit", new { id = Model.CategoriaId }, new { @class = "btn btn-info" })
        @Html.ActionLink("Retornar para a listagem de CATEGORIA", "Index", null, new { @class = "btn btn-info" })
    </div>
</div>


@Html.Partial("~/Areas/Cadastros/Views/Produtos/_PorCategoria.cshtml", Model.Produtos.ToList())


@section ScriptPage {
    <script type="text/javascript">
        $(document).ready(function () {
            $('li').removeClass("active");
            $('#liCategorias').addClass("active");
        });
    </script>
}

projeto01/Areas/Tabelas/Views/Categorias/Edit.cshtml
@model Modelo.Tabelas.Categoria


@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title =
    "Alterando os dados de uma CATEGORIA";
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="panel panel-primary">
        <div class="panel-heading">
            Alterando os dados de uma CATEGORIA
        </div>
        <div class="panel-body">
            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.CategoriaId)
                <div class="form-group">
                    @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="panel-footer panel-info">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Gravar alterações" class="btn btn-info" />
                    @Html.ActionLink("Retornar para a listagem de CATEGORIA", "Index", null, new { @class = "btn btn-warning" })
                </div>

                <br />
                <br />
            </div>
        </div>
    </div>
}


@Html.Partial("~/Areas/Cadastros/Views/Produtos/_PorCategoria.cshtml", Model.Produtos.ToList())

@section ScriptPage {
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('li').removeClass("active");
            $('#liCategorias').addClass("active");
        });
    </script>
}

projeto01/Areas/Tabelas/Views/Categorias/Index.cshtml
@model IEnumerable<Modelo.Tabelas.Categoria>   

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Listagem de Categoria";
}

@if (@TempData["Message"] != null)
{
    <div class="alert alert-success" role="alert">
        @TempData["Message"]
    </div>
}

<div class="panel panel-primary">
    <div class="panel-heading">
        Categorias registradas
    </div>
    <div class="panel-body">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.CategoriaId)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Nome)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.CategoriaId)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Nome)
                        </td>
                        <td>
                            @Html.ActionLink("Alterar", "Edit", new { id = item.CategoriaId }) |
                            @Html.ActionLink("Detalhes", "Details", new { id = item.CategoriaId }) |
                            @Html.ActionLink("Eliminar", "Delete", new { id = item.CategoriaId })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="panel-footer panel-info">
        @Html.ActionLink("Criar uma nova categoria", "Create", null, new { @class = "btn btn-success" })
    </div>
</div>

@section styles{
    <link href="@Url.Content("~/content/DataTables/css/dataTables.bootstrap.css")" rel="stylesheet" />
}

@section ScriptPage {
    <script src=" @Url.Content("~/scripts/DataTables/jquery.dataTables.js")"></script>

    <script src="@Url.Content("~/scripts/DataTables/dataTables.bootstrap.js")"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('.table').dataTable({ "order": [[1, "asc"]] });
        });
    </script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('li').removeClass("active");
            $('#liCategorias').addClass("active");
        });
    </script>
}